// ➤ The site in Spanish. `page`: the pages' own text, which the build puts into es/ (a key with
// ➤ tags in it is a whole passage with its links); `script`: what the scripts say, read by
// ➤ lib/i18n.js. The key is the English, as it stands in the page or the script.
export default {
  page: {
    'Privacy': 'Privacidad',
    'Sources': 'Fuentes',
    'Site': 'Sitio',
    'No account. No middlemen. No nonsense.': 'Sin cuenta. Sin intermediarios. Sin rodeos.',
    'Engineering, IT and technical jobs across Europe, filtered on your own device. No account. No middlemen. No nonsense.': 'Empleo de ingeniería, informática y técnico en toda Europa, filtrado en tu propio dispositivo. Sin cuenta. Sin intermediarios. Sin rodeos.',
    'Filters': 'Filtros',
    'Clear': 'Borrar',
    'Country': 'País',
    'Remote, no fixed country': 'En remoto, sin país fijo',
    'Distance': 'Distancia',
    'Occupations': 'Ocupaciones',
    'Posted': 'Publicada',
    'Any time': 'Cualquier fecha',
    'Last 24 hours': 'Últimas 24 horas',
    'Last 3 days': 'Últimos 3 días',
    'Last 7 days': 'Últimos 7 días',
    'Last 30 days': 'Últimos 30 días',
    'Last 90 days': 'Últimos 90 días',
    'Work mode': 'Modalidad',
    'On-site': 'Presencial',
    'Hybrid': 'Híbrido',
    'Remote': 'Remoto',
    '€20,000 a year': '20.000 € al año',
    '€30,000 a year': '30.000 € al año',
    '€40,000 a year': '40.000 € al año',
    '€50,000 a year': '50.000 € al año',
    '€60,000 a year': '60.000 € al año',
    '€80,000 a year': '80.000 € al año',
    '€100,000 a year': '100.000 € al año',
    'Only offers that state pay': 'Solo ofertas que indican el sueldo',
    'Level': 'Nivel',
    'Offers may ask up to': 'Que pidan como mucho',
    'any years': 'cualquier experiencia',
    '1 year': '1 año',
    '2 years': '2 años',
    '3 years': '3 años',
    '5 years': '5 años',
    '7 years': '7 años',
    '10 years': '10 años',
    '15 years': '15 años',
    'Languages': 'Idiomas',
    'Degrees': 'Titulaciones',
    'Highest degree': 'Titulación más alta',
    'not stated': 'sin indicar',
    'bachelor': 'grado',
    'master': 'máster',
    'doctorate': 'doctorado',
    'Title words': 'Palabras del título',
    'Exclude': 'Excluir',
    'Offers Listed Today': 'Ofertas publicadas hoy',
    'Dark mode': 'Modo oscuro',
    'Light or dark': 'Claro u oscuro',
    'Search': 'Buscar',
    'Title, company, town, or paste your code': 'Puesto, empresa, ciudad o pega tu código',
    'Your filters, packed. Paste it in the search bar on any visit to get them back.': 'Tus filtros, empaquetados. Pégalo en la barra de búsqueda en cualquier visita para recuperarlos.',
    'Pay, at least': 'Sueldo mínimo',
    'Any pay': 'Cualquier sueldo',
    'must appear in the title': 'deben salir en el título',
    'words that rule an offer out': 'palabras que descartan una oferta',
    "Today's offers": 'Ofertas de hoy',
    'Read my CV': 'Leer mi CV',
    'A PDF or text file, read on this device: it ticks your occupations, degrees and languages.': 'Un PDF o un archivo de texto, leído en este dispositivo: marca tus ocupaciones, titulaciones e idiomas.',
    'Your code': 'Tu código',
    'appears as you filter': 'aparece al filtrar',
    'Copy': 'Copiar',
    'Results': 'Resultados',
    'Every offer links to its source.': 'Cada oferta enlaza a su fuente.',
    'Privacy · Argus Web': 'Privacidad · Argus Web',
    'What this site does with your data.': 'Qué hace este sitio con tus datos.',
    'Your CV is read in your browser. It is not uploaded or stored.': 'Tu CV se lee en tu navegador. No se sube ni se guarda.',
    'Your code holds your filters, nothing else. It stays in the address bar, which browsers never send to servers.': 'Tu código guarda tus filtros y nada más. Se queda en la barra de direcciones, que los navegadores nunca envían a los servidores.',
    'No cookies, no storage, no analytics, no ads.': 'Sin cookies, sin almacenamiento, sin analítica, sin anuncios.',
    'Pages are served by GitHub Pages, which keeps its own <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" rel="noopener noreferrer" target="_blank">access logs</a>. Every offer links to the site it lives on, without a referrer; what those sites do is theirs. A personal, non-commercial project by the maintainer of <a href="https://github.com/JustJans/argus" rel="noopener noreferrer" target="_blank">Argus</a>. Questions or removals: <a href="https://github.com/JustJans/argus-web/issues" rel="noopener noreferrer" target="_blank">open an issue</a>.':
      'Las páginas las sirve GitHub Pages, que guarda sus propios <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" rel="noopener noreferrer" target="_blank">registros de acceso</a>. Cada oferta enlaza al sitio donde está publicada, sin decirle de dónde vienes; lo que haga ese sitio es cosa suya. Un proyecto personal y sin ánimo de lucro de quien mantiene <a href="https://github.com/JustJans/argus" rel="noopener noreferrer" target="_blank">Argus</a>. Preguntas o retiradas: <a href="https://github.com/JustJans/argus-web/issues" rel="noopener noreferrer" target="_blank">abre una incidencia</a>.',
    'Sources · Argus Web': 'Fuentes · Argus Web',
    'Where the offers come from, and under which terms.': 'De dónde vienen las ofertas, y con qué condiciones.',
    "Sources in today's pile": 'Fuentes de la lista de hoy',
    'Loading…': 'Cargando…',
    'Source': 'Fuente',
    'Licence and credit': 'Licencia y crédito',
    'The occupations, years, degrees and languages are read with the matching rules of <a href="https://github.com/JustJans/argus" rel="noopener noreferrer" target="_blank">Argus</a>, a job-search bot built for one engineer.':
      'Las ocupaciones, los años, las titulaciones y los idiomas se leen con las reglas de <a href="https://github.com/JustJans/argus" rel="noopener noreferrer" target="_blank">Argus</a>, un bot de búsqueda de empleo hecho para un ingeniero.',
    "Only sources whose written terms allow republishing are read: public employment services with open-data licences, company boards on applicant-tracking systems with a documented public API, job boards whose API asks for a link back, and employers' own careers pages, read the way search engines do (their sitemap and the JobPosting block they publish for search engines), with robots.txt obeyed. Every offer links to the page it lives on: this site shows its title, the employer and the place, never the advert's own text. To have a source or an advert removed, <a href=\"https://github.com/JustJans/argus-web/issues\" rel=\"noopener noreferrer\" target=\"_blank\">open an issue</a>; it is acted on within 72 hours. Adverts that reach the site through an intermediary's partner programme (Adzuna, Jooble, Talent.com) are shown in a section of their own, labelled, and link to the intermediary's page as those programmes require; the site sends them nothing about you.":
      'Solo se leen fuentes cuyas condiciones escritas permiten republicar: servicios públicos de empleo con licencias de datos abiertos, tableros de empresas en sistemas de selección con una API pública documentada, portales de empleo cuya API pide un enlace de vuelta, y las páginas de empleo de las propias empresas, leídas como las leen los buscadores (su mapa del sitio y el bloque JobPosting que publican para ellos), respetando robots.txt. Cada oferta enlaza a la página donde está: este sitio muestra su título, la empresa y el lugar, nunca el texto del anuncio. Para retirar una fuente o un anuncio, <a href="https://github.com/JustJans/argus-web/issues" rel="noopener noreferrer" target="_blank">abre una incidencia</a>; se atiende en 72 horas. Los anuncios que llegan por el programa de socios de un intermediario (Adzuna, Jooble, Talent.com) van en una sección aparte, señalados, y enlazan a la página del intermediario como exigen esos programas; el sitio no les envía nada sobre ti.',
    "Towns are put on the map with <a href=\"https://www.geonames.org/\" rel=\"noopener noreferrer\" target=\"_blank\">GeoNames</a> (CC BY 4.0), and occupations named with <a href=\"https://esco.ec.europa.eu/\" rel=\"noopener noreferrer\" target=\"_blank\">ESCO</a>, © European Union.":
      "Los lugares se sitúan en el mapa con <a href=\"https://www.geonames.org/\" rel=\"noopener noreferrer\" target=\"_blank\">GeoNames</a> (CC BY 4.0), y las ocupaciones se nombran con <a href=\"https://esco.ec.europa.eu/\" rel=\"noopener noreferrer\" target=\"_blank\">ESCO</a>, © Unión Europea.",
    'Not found · Argus Web': 'No encontrada · Argus Web',
    'That page does not exist.': 'Esa página no existe.',
    'Everything lives on the <a href="/argus-web/">first page</a>. Paste your code in its search bar to get your filters back.':
      'Todo está en la <a href="/argus-web/es/">primera página</a>. Pega tu código en su barra de búsqueda para recuperar tus filtros.',
    'Back to search': 'Volver a buscar',
  },
  script: {
    'Something went wrong: {error}': 'Algo ha fallado: {error}',
    'Remote': 'Remoto',
    'Country not stated': 'País sin indicar',
    'Filters': 'Filtros',
    'The sources were last read {n} days ago; some offers may have closed since.': 'Las fuentes se leyeron por última vez hace {n} días; puede que algunas ofertas hayan cerrado.',
    ' (1 part failed to download)': ' (una parte no se pudo descargar)',
    ' ({n} parts failed to download)': ' ({n} partes no se pudieron descargar)',
    ' of {pile}; choose a country or an occupation for the rest': ' de {pile}; elige un país o una ocupación para ver el resto',
    '{shown} of {total} offers': '{shown} de {total} ofertas',
    '{shown} newest offers': 'Las {shown} ofertas más recientes',
    '{shown} of the newest {total} offers; choose a country or an occupation for the rest': '{shown} de las {total} ofertas más recientes; elige un país o una ocupación para ver el resto',
    'out of {n} listed today': 'de {n} publicadas hoy',
    'newest offers': 'ofertas más recientes',
    'offer matches your filters': 'oferta encaja con tus filtros',
    'offers match your filters': 'ofertas encajan con tus filtros',
    'Downloading 1 part of the pile…': 'Descargando una parte de la lista…',
    'Downloading {n} parts of the pile…': 'Descargando {n} partes de la lista…',
    'Downloading {done} of {total}…': 'Descargando {done} de {total}…',
    'code too short': 'el código es demasiado corto',
    'code does not check out (a character is wrong or missing)': 'el código no cuadra (hay un carácter mal o falta uno)',
    'this code is from an earlier version of the page; make a new one': 'es de una versión anterior de la página; haz uno nuevo',
    'this code is from a newer version of the page': 'es de una versión más nueva de la página',
    'bad number': 'número erróneo',
    'bad word': 'palabra errónea',
    'Reading {name}…': 'Leyendo {name}…',
    'That file is too short to be a CV.': 'Ese archivo es demasiado corto para ser un CV.',
    'degrees: {list}': 'titulaciones: {list}',
    'languages: {list}': 'idiomas: {list}',
    'Ticked from your CV: {found}.': 'Marcado a partir de tu CV: {found}.',
    'Nothing of ours found in that CV; tick the filters by hand.': 'No hemos encontrado en ese CV nada de lo nuestro; marca los filtros a mano.',
    'Could not read that file ({error}).': 'No se pudo leer ese archivo ({error}).',
    'Copy': 'Copiar',
    'Copied': 'Copiado',
    'That code could not be read. Check it was copied whole.': 'Ese código no se puede leer. Comprueba que esté copiado entero.',
    'Title, company, town, or paste your code': 'Puesto, empresa, ciudad o pega tu código',
    'Title, company, town or code': 'Puesto, empresa, ciudad o código',
    'The pile is not published yet. Come back in a few hours.': 'La lista aún no está publicada. Vuelve dentro de unas horas.',
    'via {source}': 'vía {source}',
    // ➤ The two sources named by what they are, not by a name of their own.
    'employer site': 'web de la empresa',
    'Intermediary': 'intermediario',
    'asks {n}+ years': 'pide {n}+ años',
    'requires {list}': 'exige {list}',
    'degree: {list}': 'titulación: {list}',
    'Show more ({n} left)': 'Ver más (quedan {n})',
    'Via intermediaries ({n})': 'Vía intermediarios ({n})',
    '0 of {total} offers match': 'Ninguna de las {total} ofertas encaja',
    'left out by occupation': 'fuera por ocupación',
    'left out by title words': 'fuera por palabras del título',
    'left out by country': 'fuera por país',
    'left out by distance': 'fuera por distancia',
    'left out by work mode': 'fuera por modalidad',
    'left out by pay': 'fuera por sueldo',
    'On-site': 'Presencial',
    'Hybrid': 'Híbrido',
    '{pay} a year': '{pay} al año',
    '{pay} a month': '{pay} al mes',
    '{pay} a week': '{pay} a la semana',
    '{pay} a day': '{pay} al día',
    '{pay} an hour': '{pay} la hora',
    'on-site work': 'trabajo presencial',
    'hybrid work': 'trabajo híbrido',
    'remote work': 'trabajo en remoto',
    'does not say where the work is done': 'no dice dónde se trabaja',
    'does not state the pay': 'no indica el sueldo',
    'pays up to {pay} a year': 'paga como mucho {pay} al año',
    'left out by years asked': 'fuera por años pedidos',
    'left out by degree': 'fuera por titulación',
    'left out by language': 'fuera por idioma',
    'left out by posted date': 'fuera por fecha',
    'left out by search words': 'fuera por palabras de búsqueda',
    'Loosen the filters: more occupations, more countries, fewer words to avoid, a higher years cap.': 'Afloja los filtros: más ocupaciones, más países, menos palabras que evitar, un tope de años más alto.',
    'Dropped offers ({n})': 'Ofertas descartadas ({n})',
    'outside the families you chose': 'fuera de las familias elegidas',
    'outside the specialties you chose': 'fuera de las especialidades elegidas',
    'the title does not fit your roles': 'el título no encaja con tus palabras',
    'remote work, and you did not allow it': 'en remoto, y no lo permitiste',
    'in a country you did not choose ({cc})': 'en un país que no elegiste ({cc})',
    'more than {km} km from {place}': 'a más de {km} km de {place}',
    'its place is not on the map': 'su lugar no está en el mapa',
    'asks for {n} years of experience (your cap is {max})': 'pide {n} años de experiencia (tu tope es {max})',
    'requires a degree you did not list ({list})': 'exige una titulación que no indicaste ({list})',
    ' and ': ' y ',
    'The pile is not published yet.': 'La lista aún no está publicada.',
    '{n} offers, rebuilt {when} UTC.': '{n} ofertas, actualizada el {when} UTC.',
    'extracted {day}': 'extraída el {day}',
    ' or ': ' o ',
  },
};
